language: go

go:
  - "1.7.1"

install: go get -v github.com/gohugoio/hugo
# S: Build Lifecycle
script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  repo: tinysong/tinysong.github.io
  target_branch: master
  name: song
branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/tinysong/tinysong.github.io.git
