# install: go get -v github.com/gohugoio/hugo
# S: Build Lifecycle
script:
  - binaries/hugo

deploy:
  provider: blog-source
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  on:
    branch: blog-source
  local_dir: public
  repo: tinysong/tinysong.github.io
  target_branch: master
  name: tinysong
branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/tinysong/tinysong.github.io.git
