language: go

go:
  - "1.7.1"

# S: Build Lifecycle
script:
  - hugo

after_script:
  - cd ./public
  - git init
  - git config user.name "tinysong"
  - git config user.email "tinysong1226@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/tinysong/tinysong.github.io.git
